repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: local
    hooks:
      - id: backend-ruff-format
        name: Backend Ruff Format Check
        entry: bash -c 'cd trekkyfy-backend && uv run ruff format --check config.py tests'
        language: system
        pass_filenames: false

      - id: backend-ruff-lint
        name: Backend Ruff Lint
        entry: bash -c 'cd trekkyfy-backend && uv run ruff check config.py tests'
        language: system
        pass_filenames: false

      - id: backend-mypy
        name: Backend MyPy
        entry: bash -c 'cd trekkyfy-backend && uv run mypy config.py tests'
        language: system
        pass_filenames: false

      - id: backend-pytest-cov
        name: Backend Pytest Coverage
        entry: bash -c 'cd trekkyfy-backend && uv run pytest --cov=config --cov-report=term-missing'
        language: system
        pass_filenames: false
        stages: [pre-push]
